In [ ]:
import pandas as pd
import json
import unicodedata
from pathlib import Path

hotels_path = Path("hotels/hotels.csv")
if not hotels_path.exists():
    hotels_path = Path("../hotels/hotels.csv")

if not hotels_path.exists():
    raise FileNotFoundError(
        f"Could not find hotels.csv. Checked: {hotels_path.resolve()}"
    )

hotels = pd.read_csv(hotels_path, encoding="utf-8")
with open("cities.json", "r", encoding="utf-8") as file:
    cities = json.load(file)

cities_df = pd.DataFrame(cities)

def normalize_city(city):
    if pd.isna(city):
        return ""
  
    city = str(city).lower().strip()
    city = unicodedata.normalize("NFKD", city)
    city = "".join(c for c in city if not unicodedata.combining(c))

    return city

hotels["city_normalized"] = hotels["city"].apply(normalize_city)
cities_df["city_normalized"] = cities_df["name"].apply(normalize_city)

city_map = dict(zip(cities_df["city_normalized"], cities_df["id"]))

hotels["city_id"] = hotels["city_normalized"].map(city_map)

matched = hotels[hotels["city_id"].notna()].copy()
unmatched = hotels[hotels["city_id"].isna()].copy()

print("========== CITY MATCHING ==========")
print("Total hotel records:", len(hotels))
print("Matched records:", len(matched))
print("Unmatched records:", len(unmatched))

print("\nTotal hotel cities:", hotels["city_normalized"].nunique())
print("Matched cities:", matched["city_normalized"].nunique())
print("Unmatched cities:", unmatched["city_normalized"].nunique())

print("\n========== UNMATCHED CITIES ==========")
print(unmatched["city"].value_counts().head(30))

matched.to_csv("matched_hotels.csv", index=False)

print("\nmatched_hotels.csv created")

========== CITY MATCHING ==========
Total hotel records: 6000
Matched records: 3375
Unmatched records: 2625

Total hotel cities: 543
Matched cities: 148
Unmatched cities: 395

========== UNMATCHED CITIES ==========
city
bangalore         193
cochin             89
jaisalmer          79
alleppey           70
calangute          62
ooty               41
dharamshala        41
candolim           38
pushkar            37
kodaikānāl         37
baga               36
palolem            33
lonavala           32
haridwār           31
munnar             31
anjuna             30
thekkady           29
dalhousie          29
bhubaneshwar       28
kumarakom          27
katra              24
kolhapur           22
mandrem            20
darjeeling         20
salt lake city     20
varca              18
gangtok            17
ghaziabad          17
vagator            17
trivandrum         16
Name: count, dtype: int64

matched_hotels.csv created

In [94]:
print("========== UNMATCHED CITY CHECK ==========")

matched_names = set(cities_df["city_normalized"])

unmatched_cities = sorted(
    set(hotels["city_normalized"]) - matched_names
)

print("Unmatched unique cities:", len(unmatched_cities))
print()

for city in unmatched_cities:
    print(city)

========== UNMATCHED CITY CHECK ==========
Unmatched unique cities: 395


abdullapuram
abu road
adur
agonda
aguada
ahar
ahmadnagar
ajanta
alibaug
alipur
alleppey
almora
alto porvorim
ambalapulai
ambalavayal
angamali
anjuna
arambol
arpora
attibele
attigundi
auroville
avathi
badami
baddi
badshahpur
baga
baghdogra
bajaura
balighai
ballygunge
bambolim
banar
bangalore
bapane
bara bazar
barddhaman
bardez
bareilly
barkur
basari
bashist
bayappanhalli
beawar
begur
behala
behror
belgaum
belparao
belur
benaulim
betalbatim
bhatkal
bhilai
bhim tal
bhimadolu
bhimashankar
bhiwadi
bhubaneshwar
bhurtuk
bijni
binsar
bir
bodh gaya
bolpur
bordi
bori
buin
bulandshahr
bundi
calangute
canacona
candolim
carmona
cavelossim
chakan
chamba
chandoli
chandrapur
chegat
cherai beach
chhapar
chikalthan
chikmagalur
chinchwad
chinnakanal
chitradurga
chopdem
chottanikara
churi jodhan
churu
cochin
collem
colva
coonoor
curca
dagshai
dahej
dalhousie
dam dam
daman
dapoli
darjeeling
daulatabad
davangere
dedha
delmara
delwara
dentam
deskit
devanhalli
dewas
dhampur
dhand
dhantoli
dharamshala
dharmsala
dharuhera
diamond harbour
digha
diva
dive
dona paula
durgapur
durgjan
dwarka
eramalloor
faizabad
ganeshgudi
ganganagar
gangapur
gangtok
ganpatipule
garjia
ghansoli
ghaziabad
gokarna
gonikoppal
gopalpur
gorakhpur
greater noida
guduvancheri
guhagar
gulmarg
guruvayur
gwaldam
haddo
haidar sahibguda
hampi
hanumangarh
haridwar
haripur
harsola
hasanganj
hassan
himatnagar
hodal
hoshangabad
hospet
hosur
hubli
hundar
indirapuram
jadabpur
jahangir
jaisalmer
jalna
janla
jawalapur
jhalamand
kakkabe
kakkanad
kala
kalamboli
kalapettai
kalkaji devi
kallar
kalpatta
kalundri
kalyani
kambam
kammasandra
kanatal
kanchipuram
kandaghat
kanha
kaniyambetta
kankhal
kanyakumari
kapkot
kapurwahal
kargil
karsiyang
kas
kasauli
kasol
katra
kattappana
kausani
kaza
kelambakkam
ketti
khairla
khajuraho
kharadi
khari rohar
kharsia
khawasa
khilchipur
khimsar
kiar
kiluparamba
kodaikanal
kolara
kolhapur
kolluru
kotagiri
kotamangalam
kottakamboor
kovalam
krishnarajasagara
kulan
kumarakom
kumbakonam
kumbhalgarh
kumudi
kurandi
kushalnagar
lamaj
lanja
lansdowne
lavasa
leh
liluah
lokpal
lonavala
loutolim
lukerganj
madgaon
mahabaleshwar
mahabalipuram
mahiravani
majorda
majra
malaut
mananthavady
mandarmoni
mandrem
manesar
mangalore
manganam
manimala
manipala
maraiyur
maranhalli
mararikulam
marwad
mashobra
masinagudi
matheran
mcleod ganj
meppadi
minjur
mohwa kalan
morjim
mubarikpur
mundra
munnar
munroe island
murud
muthanga
muttupet
nagarbazar
nagchala
nagwa
nai
naldera
nandi
narela
narendranagar
narkanda
navi mumbai
naya bazar
nedumbassery
neemrana
neil island
nerul
nileshwar
nubra
ooty
oragadam
pachmarhi
pahalgam
paithalmala
palni
palolem
panchagani
panchgani
paradip garh
paravur
parra
patipukur
patnem
payyannur
perumbalam
pimpri
pipalkoti
punnappira
pura raghunath
purnankuppam
pushkar
puvar
raiwala
rajpur
rama
ramakkalmedu
rameswaram
ranikhet
ranjangaon ganpati
ravangla
razole
rhenok
rinchingpong
salcete
salt lake city
sam
sangolda
sarkhej
sasan gir
secunderabad
shamshi
shanti niketan
shertallai
shimoga
shirwal
shogi
siddapur
sika
sinquerim
siolim
sitapur muafi
somnath
somvarpet
sriperumbudur
srirangam
srivardhan
subrahmanya
sultan bathery
suntikoppa
tajganj
takdah
tala
tambaram
tangra
tapovan
tapukrah
tekkumuri
thaska miranji
thekkady
tiruchchirappalli
tiruchengodu
tirupporur
tiruvallam
trichur
trivandrum
tughlakabad
turambhe
udaipura
unchagao
uttarkashi
vadakkancheri
vaduvanchal
vagator
vallam
valudavur
vandalur
vandanmedu
vandiperiyar
varca
vasco da gama
vayalar
velanganni
velcao
verem
vettutura
villianur
virajpet
vythiri
wayanad
wellington
wynchpet
yelagiri
yelahanka
yercaud

In [95]:
import pandas as pd
import json
import unicodedata
from rapidfuzz import process, fuzz

hotels = pd.read_csv("hotels/hotels.csv")

with open("cities.json", "r", encoding="utf-8") as file:
    cities = json.load(file)

cities_df = pd.DataFrame(cities)

def normalize_city(city):
    if pd.isna(city):
        return ""

    city = str(city).lower().strip()
    city = unicodedata.normalize("NFKD", city)
    city = "".join(c for c in city if not unicodedata.combining(c))

    return city

hotels["city_normalized"] = hotels["city"].apply(normalize_city)
cities_df["city_normalized"] = cities_df["name"].apply(normalize_city)

city_map = dict(zip(cities_df["city_normalized"], cities_df["id"]))

hotels["city_id"] = hotels["city_normalized"].map(city_map)

unmatched = hotels[hotels["city_id"].isna()].copy()

city_names = cities_df["city_normalized"].tolist()

print("========== FUZZY CITY MATCHING ==========")

for city in sorted(unmatched["city_normalized"].unique()):
    result = process.extractOne(
        city,
        city_names,
        scorer=fuzz.ratio
    )

    print(city, "->", result)

========== FUZZY CITY MATCHING ==========
 -> ('mumbai', 0.0, 0)
abdullapuram -> ('malappuram', 72.72727272727273, 328)
abu road -> ('habra', 61.53846153846154, 230)
adur -> ('tandur', 80.0, 486)
agonda -> ('nagda', 72.72727272727273, 332)
aguada -> ('nagda', 72.72727272727273, 332)
ahar -> ('lahar', 88.88888888888889, 794)
ahmadnagar -> ('ahmednagar', 90.0, 105)
ajanta -> ('anantnag', 71.42857142857143, 304)
alibaug -> ('hazaribag', 62.5, 241)
alipur -> ('lalitpur', 85.71428571428572, 251)
alleppey -> ("o' valley", 58.82352941176471, 1123)
almora -> ('amroha', 66.66666666666667, 45)
alto porvorim -> ('taraori', 50.0, 1002)
ambalapulai -> ('amalapuram', 76.19047619047619, 584)
ambalavayal -> ('malavalli', 70.0, 792)
angamali -> ('sangli', 71.42857142857143, 76)
anjuna -> ('anjar', 72.72727272727273, 378)
arambol -> ('baramula', 66.66666666666667, 200)
arpora -> ('warora', 83.33333333333334, 657)
attibele -> ('attingal', 62.5, 766)
attigundi -> ('pattamundai', 70.0, 851)
auroville -> ('arvi', 61.53846153846154, 697)
avathi -> ('athni', 72.72727272727273, 664)
badami -> ('nadbai', 66.66666666666667, 991)
baddi -> ('kadi', 66.66666666666667, 429)
badshahpur -> ('shahpur', 82.35294117647058, 743)
baga -> ('bagaha', 80.0, 290)
baghdogra -> ('bagaha', 66.66666666666667, 290)
bajaura -> ('rajura', 76.92307692307692, 1007)
balighai -> ('balaghat', 75.0, 387)
ballygunge -> ('lunglei', 58.82352941176471, 546)
bambolim -> ('ambejogai', 58.82352941176471, 423)
banar -> ('anjar', 80.0, 378)
bangalore -> ('bengaluru', 66.66666666666667, 2)
bapane -> ('panvel', 66.66666666666667, 164)
bara bazar -> ('raxaul bazar', 72.72727272727273, 714)
barddhaman -> ('baramula', 66.66666666666667, 200)
bardez -> ('barmer', 66.66666666666667, 175)
bareilly -> ('barbil', 71.42857142857143, 473)
barkur -> ('bankura', 76.92307692307692, 246)
basari -> ('ballari', 76.92307692307692, 95)
bashist -> ('nashik', 61.53846153846154, 24)
bayappanhalli -> ('bhawanipatna', 56.00000000000001, 456)
beawar -> ('alwar', 72.72727272727273, 111)
begur -> ('bengaluru', 71.42857142857143, 2)
behala -> ('bhopal', 66.66666666666667, 16)
behror -> ('sehore', 66.66666666666667, 355)
belgaum -> ('belagavi', 66.66666666666667, 82)
belparao -> ('belagavi', 62.5, 82)
belur -> ('eluru', 80.0, 160)
benaulim -> ('tenali', 71.42857142857143, 204)
betalbatim -> ('batala', 62.5, 213)
bhatkal -> ('batala', 76.92307692307692, 213)
bhilai -> ('bhiwani', 76.92307692307692, 169)
bhim tal -> ('bhopal', 57.14285714285714, 16)
bhimadolu -> ('shahdol', 62.5, 406)
bhimashankar -> ('bhimavaram', 63.63636363636363, 242)
bhiwadi -> ('bhiwandi', 93.33333333333333, 58)
bhubaneshwar -> ('bhubaneswar', 95.65217391304348, 53)
bhurtuk -> ('bharatpur', 62.5, 140)
bijni -> ('bhiwani', 66.66666666666667, 169)
binsar -> ('bhainsa', 76.92307692307692, 623)
bir -> ('bikaner', 60.0, 62)
bodh gaya -> ('bodhan', 66.66666666666667, 411)
bolpur -> ('solapur', 76.92307692307692, 49)
bordi -> ('orai', 66.66666666666667, 177)
bori -> ('orai', 75.0, 177)
buin -> ('ujjain', 60.0, 75)
bulandshahr -> ('jalandhar', 70.0, 51)
bundi -> ('mundi', 80.0, 908)
calangute -> ('palanpur', 58.82352941176471, 257)
canacona -> ('jangaon', 66.66666666666667, 591)
candolim -> ('adoni', 61.53846153846154, 201)
carmona -> ('arakkonam', 62.5, 408)
cavelossim -> ('vellakoil', 52.63157894736843, 731)
chakan -> ('ichalkaranji', 66.66666666666667, 122)
chamba -> ('habra', 72.72727272727273, 230)
chandoli -> ('hardoi', 71.42857142857143, 291)
chandrapur -> ('ramachandrapuram', 76.92307692307692, 718)
chegat -> ('chatra', 66.66666666666667, 618)
cherai beach -> ('bahraich', 60.0, 178)
chhapar -> ('chhapra', 85.71428571428572, 143)
chikalthan -> ('chirala', 70.58823529411764, 377)
chikmagalur -> ('chikkamagaluru', 88.0, 272)
chinchwad -> ('bhiwandi', 58.82352941176471, 58)
chinnakanal -> ('dhenkanal', 70.0, 461)
chitradurga -> ('chirala', 66.66666666666667, 377)
chopdem -> ('pacode', 61.53846153846154, 1094)
chottanikara -> ('chandigarh', 63.63636363636363, 43)
churi jodhan -> ('shrigonda', 57.14285714285714, 993)
churu -> ('raayachuru', 66.66666666666667, 163)
cochin -> ('kochi', 72.72727272727273, 67)
collem -> ('kollam', 66.66666666666667, 106)
colva -> ('akola', 60.0, 91)
coonoor -> ('noorpur', 57.14285714285714, 745)
curca -> ('tura', 66.66666666666667, 419)
dagshai -> ('bageshwar', 62.5, 1208)
dahej -> ('mahe', 66.66666666666667, 773)
dalhousie -> ('delhi', 57.14285714285714, 1)
dam dam -> ('ramagundam', 58.82352941176471, 145)
daman -> ('samana', 72.72727272727273, 656)
dapoli -> ('rudauli', 61.53846153846154, 775)
darjeeling -> ('darjiling', 84.21052631578947, 271)
daulatabad -> ('allahabad', 73.6842105263158, 36)
davangere -> ('davanagere', 94.73684210526316, 89)
dedha -> ('deoghar', 66.66666666666667, 165)
delmara -> ('margao', 61.53846153846154, 353)
delwara -> ('talwara', 71.42857142857143, 1193)
dentam -> ('natham', 66.66666666666667, 1060)
deskit -> ('delhi', 54.54545454545454, 1)
devanhalli -> ('dhenkanal', 63.1578947368421, 461)
dewas -> ('rewa', 66.66666666666667, 186)
dhampur -> ('udhampur', 93.33333333333333, 798)
dhand -> ('dhanbad', 83.33333333333334, 32)
dhantoli -> ('dhamtari', 62.5, 393)
dharamshala -> ('bhadrachalam', 69.56521739130434, 616)
dharmsala -> ('dharmavaram', 70.0, 268)
dharuhera -> ('pandharpur', 63.1578947368421, 359)
diamond harbour -> ('pandharpur', 64.0, 359)
digha -> ('deoghar', 66.66666666666667, 165)
diva -> ('gudivada', 66.66666666666667, 273)
dive -> ('sadasivpet', 57.14285714285714, 783)
dona paula -> ('ottappalam', 60.0, 576)
durgapur -> ('rudrapur', 75.0, 366)
durgjan -> ('durg', 72.72727272727273, 130)
dwarka -> ('pindwara', 71.42857142857143, 1170)
eramalloor -> ('perambalur', 70.0, 762)
faizabad -> ('firozabad', 82.35294117647058, 19)
ganeshgudi -> ('panagudi', 66.66666666666667, 1015)
ganganagar -> ('kagaznagar', 80.0, 540)
gangapur -> ('gangarampur', 84.21052631578947, 555)
gangtok -> ('mangrol', 57.14285714285714, 553)
ganpatipule -> ('santipur', 63.1578947368421, 223)
garjia -> ('sangaria', 71.42857142857143, 808)
ghansoli -> ('hansi', 76.92307692307692, 380)
ghaziabad -> ('adilabad', 70.58823529411764, 277)
gokarna -> ('karnal', 76.92307692307692, 124)
gonikoppal -> ('sonipat', 58.82352941176471, 151)
gopalpur -> ('palanpur', 75.0, 257)
gorakhpur -> ('zirakpur', 70.58823529411764, 345)
greater noida -> ('urmar tanda', 58.33333333333333, 1068)
guduvancheri -> ('nandivaram-guduvancheri', 68.57142857142857, 685)
guhagar -> ('sagar', 66.66666666666667, 114)
gulmarg -> ('umarga', 76.92307692307692, 799)
guruvayur -> ('guruvayoor', 84.21052631578947, 1175)
gwaldam -> ('palladam', 66.66666666666667, 907)
haddo -> ('hardoi', 72.72727272727273, 291)
haidar sahibguda -> ('jharsuguda', 61.53846153846154, 341)
hampi -> ('shamli', 72.72727272727273, 361)
hanumangarh -> ('ramngarh', 73.6842105263158, 937)
haridwar -> ('hardwar', 93.33333333333333, 150)
haripur -> ('hajipur', 85.71428571428572, 232)
harsola -> ('saharsa', 71.42857142857143, 216)
hasanganj -> ('asarganj', 82.35294117647058, 1213)
hassan -> ('pasan', 72.72727272727273, 918)
himatnagar -> ('dharmanagar', 76.19047619047619, 897)
hodal -> ('bhopal', 72.72727272727273, 16)
hoshangabad -> ('osmanabad', 80.0, 293)
hospet -> ('suryapet', 57.14285714285714, 309)
hosur -> ('hoshiarpur', 66.66666666666667, 199)
hubli -> ('dhubri', 72.72727272727273, 491)
hundar -> ('mundargi', 71.42857142857143, 1179)
indirapuram -> ('narasapuram', 72.72727272727273, 526)
jadabpur -> ('jagdalpur', 82.35294117647058, 261)
jahangir -> ('balangir', 75.0, 339)
jaisalmer -> ('jagtial', 62.5, 342)
jalna -> ('jalandhar', 71.42857142857143, 51)
janla -> ('mandla', 72.72727272727273, 516)
jawalapur -> ('jabalpur', 82.35294117647058, 38)
jhalamand -> ('jalandhar', 66.66666666666667, 51)
kakkabe -> ('kakinada', 53.333333333333336, 112)
kakkanad -> ('kakinada', 75.0, 112)
kala -> ('koratla', 72.72727272727273, 474)
kalamboli -> ('kavali', 66.66666666666667, 392)
kalapettai -> ('udumalaipettai', 75.0, 511)
kalkaji devi -> ('malkangiri', 54.54545454545454, 1081)
kallar -> ('ballari', 76.92307692307692, 95)
kalpatta -> ('kolkata', 66.66666666666667, 6)
kalundri -> ('kadiri', 71.42857142857143, 364)
kalyani -> ('palani', 76.92307692307692, 465)
kambam -> ('khammam', 76.92307692307692, 182)
kammasandra -> ('mahesana', 63.1578947368421, 183)
kanatal -> ('karnal', 76.92307692307692, 124)
kanchipuram -> ('kancheepuram', 86.95652173913044, 205)
kandaghat -> ('ranaghat', 82.35294117647058, 235)
kanha -> ('karnal', 72.72727272727273, 124)
kaniyambetta -> ('vaniyambadi', 69.56521739130434, 350)
kankhal -> ('karnal', 76.92307692307692, 124)
kanyakumari -> ('kayamkulam', 66.66666666666667, 457)
kapkot -> ('akot', 80.0, 354)
kapurwahal -> ('kapurthala', 80.0, 325)
kargil -> ('karaikal', 71.42857142857143, 379)
karsiyang -> ('karimganj', 66.66666666666667, 547)
kas -> ('tenkasi', 60.0, 449)
kasauli -> ('kavali', 76.92307692307692, 392)
kasol -> ('asansol', 66.66666666666667, 71)
katra -> ('karnal', 72.72727272727273, 124)
kattappana -> ('ottappalam', 70.0, 576)
kausani -> ('sarni', 66.66666666666667, 351)
kaza -> ('aizawl', 60.0, 121)
kelambakkam -> ('namakkal', 63.1578947368421, 566)
ketti -> ('bettiah', 66.66666666666667, 252)
khairla -> ('khair', 83.33333333333334, 323)
khajuraho -> ('kharar', 66.66666666666667, 421)
kharadi -> ('hardoi', 76.92307692307692, 291)
khari rohar -> ('kharar', 70.58823529411764, 421)
kharsia -> ('kharar', 76.92307692307692, 421)
khawasa -> ('phagwara', 66.66666666666667, 322)
khilchipur -> ('kashipur', 66.66666666666667, 269)
khimsar -> ('hisar', 83.33333333333334, 116)
kiar -> ('katihar', 72.72727272727273, 149)
kiluparamba -> ('taliparamba', 72.72727272727273, 434)
kodaikanal -> ('karaikal', 66.66666666666667, 379)
kolara -> ('kolar', 90.9090909090909, 245)
kolhapur -> ('solapur', 80.0, 49)
kolluru -> ('eluru', 66.66666666666667, 160)
kotagiri -> ('venkatagiri', 73.6842105263158, 598)
kotamangalam -> ('tharamangalam', 80.0, 901)
kottakamboor -> ('kottayam', 70.0, 563)
kovalam -> ('kollam', 76.92307692307692, 106)
krishnarajasagara -> ('raisinghnagar', 60.0, 960)
kulan -> ('pulgaon', 66.66666666666667, 782)
kumarakom -> ('margao', 66.66666666666667, 353)
kumbakonam -> ('arakkonam', 63.1578947368421, 408)
kumbhalgarh -> ('sabalgarh', 70.0, 822)
kumudi -> ('mundi', 72.72727272727273, 908)
kurandi -> ('surandai', 80.0, 946)
kushalnagar -> ('bhavnagar', 70.0, 69)
lamaj -> ('lalganj', 66.66666666666667, 1080)
lanja -> ('anjar', 80.0, 378)
lansdowne -> ('nandgaon', 58.82352941176471, 1203)
lavasa -> ('silvassa', 71.42857142857143, 1128)
leh -> ('loha', 57.14285714285714, 1187)
liluah -> ('aligarh', 61.53846153846154, 48)
lokpal -> ('losal', 72.72727272727273, 935)
lonavala -> ('lonavla', 93.33333333333333, 538)
loutolim -> ('malout', 57.14285714285714, 447)
lukerganj -> ('mukerian', 70.58823529411764, 1144)
madgaon -> ('malegaon', 80.0, 86)
mahabaleshwar -> ('bageshwar', 72.72727272727273, 1208)
mahabalipuram -> ('mahalingapura', 76.92307692307692, 896)
mahiravani -> ('mariani', 70.58823529411764, 1156)
majorda -> ('malda', 66.66666666666667, 1077)
majra -> ('margao', 72.72727272727273, 353)
malaut -> ('malout', 83.33333333333334, 447)
mananthavady -> ('manavadar', 66.66666666666667, 964)
mandarmoni -> ('mandamarri', 70.0, 471)
mandrem -> ('mandsaur', 66.66666666666667, 243)
manesar -> ('mansa', 83.33333333333334, 433)
mangalore -> ('mangaluru', 77.77777777777779, 84)
manganam -> ('ramanagaram', 73.6842105263158, 401)
manimala -> ('nirmal', 71.42857142857143, 369)
manipala -> ('mandla', 71.42857142857143, 516)
maraiyur -> ('markapur', 75.0, 530)
maranhalli -> ('manali', 75.0, 1217)
mararikulam -> ('araria', 70.58823529411764, 404)
marwad -> ('mhaswad', 76.92307692307692, 1176)
mashobra -> ('sihora', 71.42857142857143, 757)
masinagudi -> ('mainaguri', 84.21052631578947, 975)
matheran -> ('mathura', 80.0, 683)
mcleod ganj -> ('malegaon', 63.1578947368421, 86)
meppadi -> ('mandi', 66.66666666666667, 517)
minjur -> ('medinipur', 66.66666666666667, 229)
mohwa kalan -> ('palia kalan', 63.63636363636363, 803)
morjim -> ('morvi', 72.72727272727273, 176)
mubarikpur -> ('markapur', 77.77777777777779, 530)
mundra -> ('mundi', 72.72727272727273, 908)
munnar -> ('unnao', 72.72727272727273, 187)
munroe island -> ('mukerian', 57.14285714285714, 1144)
murud -> ('manuguru', 61.53846153846154, 848)
muthanga -> ('thangadh', 75.0, 705)
muttupet -> ('muvattupuzha', 60.0, 924)
nagarbazar -> ('mahnar bazar', 72.72727272727273, 765)
nagchala -> ('nagla', 76.92307692307692, 1114)
nagwa -> ('nagda', 80.0, 332)
nai -> ('niwai', 75.0, 1207)
naldera -> ('adra', 72.72727272727273, 1199)
nandi -> ('anand', 80.0, 172)
narela -> ('nagla', 72.72727272727273, 1114)
narendranagar -> ('taranagar', 72.72727272727273, 853)
narkanda -> ('narwana', 80.0, 497)
navi mumbai -> ('mumbai', 70.58823529411764, 0)
naya bazar -> ('raxaul bazar', 72.72727272727273, 714)
nedumbassery -> ('nandurbar', 57.14285714285714, 295)
neemrana -> ('makrana', 66.66666666666667, 358)
neil island -> ('yellandu', 63.1578947368421, 832)
nerul -> ('narnaul', 66.66666666666667, 420)
nileshwar -> ('ankleshwar', 84.21052631578947, 424)
nubra -> ('bankura', 66.66666666666667, 246)
ooty -> ('gooty', 88.88888888888889, 636)
oragadam -> ('rayagada', 75.0, 537)
pachmarhi -> ('pathardi', 70.58823529411764, 1092)
pahalgam -> ('patiala', 66.66666666666667, 26)
paithalmala -> ('perinthalmanna', 72.0, 677)
palni -> ('palani', 90.9090909090909, 465)
palolem -> ('palacole', 80.0, 413)
panchagani -> ('panagar', 70.58823529411764, 1021)
panchgani -> ('panchla', 75.0, 1119)
paradip garh -> ('raigarh', 73.6842105263158, 282)
paravur -> ('paravoor', 80.0, 746)
parra -> ('arrah', 80.0, 136)
patipukur -> ('patur', 71.42857142857143, 1172)
patnem -> ('patna', 72.72727272727273, 13)
payyannur -> ('panniyannur', 80.0, 1163)
perumbalam -> ('perambalur', 70.0, 762)
pimpri -> ('pipariya', 71.42857142857143, 679)
pipalkoti -> ('panipat', 62.5, 118)
punnappira -> ('purnia', 62.5, 173)
pura raghunath -> ('raghunathpur', 69.23076923076923, 1124)
purnankuppam -> ('kunnamkulam', 60.86956521739131, 571)
pushkar -> ('sikar', 66.66666666666667, 179)
puvar -> ('puri', 66.66666666666667, 210)
raiwala -> ('patiala', 71.42857142857143, 26)
rajpur -> ('rajpura', 92.3076923076923, 391)
rama -> ('ramgarh', 72.72727272727273, 297)
ramakkalmedu -> ('namakkal', 70.0, 566)
rameswaram -> ('rameshwaram', 95.23809523809523, 754)
ranikhet -> ('ranipet', 80.0, 134)
ranjangaon ganpati -> ('anjangaon', 66.66666666666667, 552)
ravangla -> ('rangia', 71.42857142857143, 1024)
razole -> ('repalle', 61.53846153846154, 701)
rhenok -> ('renukoot', 57.14285714285714, 470)
rinchingpong -> ('raisinghnagar', 56.00000000000001, 960)
salcete -> ('salem', 66.66666666666667, 54)
salt lake city -> ('merta city', 58.33333333333333, 732)
sam -> ('salem', 75.0, 54)
sangolda -> ('sangole', 80.0, 947)
sarkhej -> ('narkhed', 71.42857142857143, 1152)
sasan gir -> ('balangir', 70.58823529411764, 339)
secunderabad -> ('sikandrabad', 69.56521739130434, 452)
shamshi -> ('shamli', 76.92307692307692, 361)
shanti niketan -> ('nainital', 54.54545454545454, 717)
shertallai -> ('cherthala', 73.6842105263158, 665)
shimoga -> ('shivamogga', 82.35294117647058, 127)
shirwal -> ('sira', 72.72727272727273, 615)
shogi -> ('bhongir', 66.66666666666667, 583)
siddapur -> ('sitapur', 80.0, 221)
sika -> ('sikar', 88.88888888888889, 179)
sinquerim -> ('suri', 61.53846153846154, 505)
siolim -> ('sirohi', 66.66666666666667, 797)
sitapur muafi -> ('sitapur', 70.0, 221)
somnath -> ('sonipat', 71.42857142857143, 151)
somvarpet -> ('barpeta', 62.5, 699)
sriperumbudur -> ('shrirampur', 60.86956521739131, 365)
srirangam -> ('siana', 71.42857142857143, 742)
srivardhan -> ('sardhana', 77.77777777777779, 639)
subrahmanya -> ('samana', 70.58823529411764, 656)
sultan bathery -> ('sultanpur', 60.86956521739131, 331)
suntikoppa -> ('sonipat', 58.82352941176471, 151)
tajganj -> ('tirwaganj', 75.0, 1049)
takdah -> ('tanda', 72.72727272727273, 346)
tala -> ('batala', 80.0, 213)
tambaram -> ('sasaram', 66.66666666666667, 231)
tangra -> ('agra', 80.0, 22)
tapovan -> ('kapadvanj', 62.5, 628)
tapukrah -> ('sitapur', 66.66666666666667, 221)
tekkumuri -> ('tumkur', 66.66666666666667, 115)
thaska miranji -> ('ichalkaranji', 69.23076923076923, 122)
thekkady -> ('tharad', 57.14285714285714, 949)
tiruchchirappalli -> ('tiruchirappalli', 93.75, 52)
tiruchengodu -> ('tiruchengode', 91.66666666666666, 347)
tirupporur -> ('tiruppur', 88.88888888888889, 88)
tiruvallam -> ('thiruvalla', 90.0, 587)
trichur -> ('thrissur', 66.66666666666667, 110)
trivandrum -> ('tandur', 62.5, 486)
tughlakabad -> ('shahabad', 63.1578947368421, 472)
turambhe -> ('tura', 66.66666666666667, 419)
udaipura -> ('udaipur', 93.33333333333333, 68)
unchagao -> ('uchgaon', 80.0, 890)
uttarkashi -> ('itarsi', 62.5, 337)
vadakkancheri -> ('mancherial', 60.86956521739131, 275)
vaduvanchal -> ('bhadrachalam', 60.86956521739131, 616)
vagator -> ('sagar', 66.66666666666667, 114)
vallam -> ('palladam', 71.42857142857143, 907)
valudavur -> ('vadalur', 75.0, 738)
vandalur -> ('vadalur', 93.33333333333333, 738)
vandanmedu -> ('anand', 66.66666666666667, 172)
vandiperiyar -> ('periyasemur', 60.86956521739131, 876)
varca -> ('vyara', 80.0, 736)
vasco da gama -> ('ashok nagar', 58.33333333333333, 394)
vayalar -> ('varkala', 71.42857142857143, 726)
velanganni -> ('belagavi', 66.66666666666667, 82)
velcao -> ('vellakoil', 66.66666666666667, 731)
verem -> ('vellore', 66.66666666666667, 180)
vettutura -> ('tura', 61.53846153846154, 419)
villianur -> ('phillaur', 70.58823529411764, 1111)
virajpet -> ('rajampet', 75.0, 302)
vythiri -> ('tehri', 66.66666666666667, 1017)
wayanad -> ('powayan', 71.42857142857143, 1070)
wellington -> ('nongstoin', 52.63157894736843, 934)
wynchpet -> ('narayanpet', 55.55555555555556, 713)
yelagiri -> ('yadgir', 71.42857142857143, 422)
yelahanka -> ('lanka', 71.42857142857143, 774)
yercaud -> ('hyderabad', 62.5, 4)

In [96]:
city_aliases = {
    "bangalore": "bengaluru",
    "cochin": "kochi",
    "calcutta": "kolkata",
    "trivandrum": "thiruvananthapuram",
    "alleppey": "alappuzha",
    "ooty": "udhagamandalam",
    "baroda": "vadodara",
    "pondicherry": "puducherry",
    "benaras": "varanasi",
    "benares": "varanasi",
    "ahmadnagar": "ahmednagar"
}

In [97]:
hotels["canonical_city"] = hotels["city_normalized"].replace(city_aliases)

hotels["city_id"] = hotels["canonical_city"].map(
    dict(zip(cities_df["city_normalized"], cities_df["id"]))
)

In [98]:
print("Total hotels:", len(hotels))
print("Matched:", hotels["city_id"].notna().sum())
print("Unmatched:", hotels["city_id"].isna().sum())

Total hotels: 6000
Matched: 3764
Unmatched: 2236

In [99]:
alias_rows = hotels[hotels["city_normalized"].isin(city_aliases)]

print(alias_rows[
    ["city", "canonical_city", "state", "city_id"]
].drop_duplicates().to_string(index=False))

       city     canonical_city       state city_id
       ooty     udhagamandalam  Tamil Nadu     371
  bangalore          bengaluru   Karnataka       3
   alleppey          alappuzha      Kerala     193
     cochin              kochi      Kerala      68
 trivandrum thiruvananthapuram      Kerala      58
pondicherry         puducherry Pondicherry     NaN
 ahmadnagar         ahmednagar Maharashtra     106

In [100]:
print("Exact matches:", exact_match.sum())
print("After verified aliases:", hotels["city_id"].notna().sum())
print("Still unmatched:", hotels["city_id"].isna().sum())

Exact matches: 3375
After verified aliases: 3764
Still unmatched: 2236

In [101]:
unmatched = hotels[hotels["city_id"].isna()]

print("Unmatched unique cities:", unmatched["canonical_city"].nunique())
print("\nTop unmatched cities:")
print(unmatched["canonical_city"].value_counts().head(30))

Unmatched unique cities: 390

Top unmatched cities:
canonical_city
jaisalmer         79
calangute         62
dharamshala       41
candolim          38
pushkar           37
kodaikanal        37
baga              36
puducherry        34
palolem           33
lonavala          32
haridwar          31
munnar            31
anjuna            30
thekkady          29
dalhousie         29
bhubaneshwar      28
kumarakom         27
katra             24
kolhapur          22
mandrem           20
darjeeling        20
salt lake city    20
varca             18
                  18
gangtok           17
ghaziabad         17
vagator           17
khajuraho         16
greater noida     16
mcleod ganj       16
Name: count, dtype: int64

In [102]:
cleaned_hotels = hotels[
    hotels["city_id"].notna() &
    hotels["property_name"].notna() &
    hotels["property_id"].notna()
].copy()

print("Rows:", len(cleaned_hotels))

Rows: 3394

In [103]:
cleaned_hotels["site_review_count"] = pd.to_numeric(
    cleaned_hotels["site_review_count"],
    errors="coerce"
)

In [104]:
print(cleaned_hotels["site_review_count"].dtype)

float64

In [105]:
cleaned_hotels["hotel_star_rating"] = (
    cleaned_hotels["hotel_star_rating"]
    .str.extract(r"(\d+\.?\d*)")[0]
    .astype(float)
)

In [106]:
city_names = set(cities_df["city_normalized"])

for old, new in city_aliases.items():
    if new in city_names:
        print(old, "->", new)
    else:
        print("NOT FOUND:", old, "->", new)

bangalore -> bengaluru
cochin -> kochi
calcutta -> kolkata
trivandrum -> thiruvananthapuram
alleppey -> alappuzha
ooty -> udhagamandalam
baroda -> vadodara
NOT FOUND: pondicherry -> puducherry
benaras -> varanasi
benares -> varanasi
ahmadnagar -> ahmednagar

In [107]:
hotels[["city", "state"]].head(20)

              city             state
0            pauri       Uttarakhand
1             ooty        Tamil Nadu
2        pīpalkoti       Uttarakhand
3        kumarakom            Kerala
4        kumarakom            Kerala
5             ooty        Tamil Nadu
6           manāli  Himachal Pradesh
7         haridwār       Uttarakhand
8        kumarakom            Kerala
9   pura raghunāth     Uttar Pradesh
10       kalimpong       West Bengal
11      tiruvallam            Kerala
12          mysore         Karnataka
13        haridwār       Uttarakhand
14            ooty        Tamil Nadu
15     ganpatipule       Maharashtra
16          munnar            Kerala
17         gurgaon           Haryana
18    vandiperiyār            Kerala
19           solan  Himachal Pradesh

In [108]:
cities_df.head(20)

    id           name           state city_normalized
0    1         Mumbai     Maharashtra          mumbai
1    2          Delhi           Delhi           delhi
2    3      Bengaluru       Karnataka       bengaluru
3    4      Ahmedabad         Gujarat       ahmedabad
4    5      Hyderabad       Telangana       hyderabad
5    6        Chennai      Tamil Nadu         chennai
6    7        Kolkata     West Bengal         kolkata
7    8           Pune     Maharashtra            pune
8    9         Jaipur       Rajasthan          jaipur
9   10          Surat         Gujarat           surat
10  11        Lucknow   Uttar Pradesh         lucknow
11  12         Kanpur   Uttar Pradesh          kanpur
12  13         Nagpur     Maharashtra          nagpur
13  14          Patna           Bihar           patna
14  15         Indore  Madhya Pradesh          indore
15  16          Thane     Maharashtra           thane
16  17         Bhopal  Madhya Pradesh          bhopal
17  18  Visakhapatnam  Andhra Pradesh   visakhapatnam
18  19       Vadodara         Gujarat        vadodara
19  20      Firozabad   Uttar Pradesh       firozabad

In [109]:
print("Hotels with city:", hotels["city"].notna().sum())
print("Hotels with state:", hotels["state"].notna().sum())
print("Cities with state:", cities_df["state"].notna().sum())

Hotels with city: 5982
Hotels with state: 5951
Cities with state: 1221

In [110]:
exact_match = hotels["city_normalized"].isin(set(cities_df["city_normalized"]))

print("Exact matched hotels:", exact_match.sum())
print("Exact unmatched hotels:", (~exact_match).sum())

Exact matched hotels: 3375
Exact unmatched hotels: 2625

In [111]:
cleaned_hotels["hotel_star_rating"] = (
    cleaned_hotels["hotel_star_rating"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")[0]
    .astype(float)
)
print(cleaned_hotels["hotel_star_rating"].value_counts(dropna=False).sort_index())

hotel_star_rating
1.0     169
2.0     422
3.0     816
4.0     166
5.0     114
NaN    1707
Name: count, dtype: int64

In [112]:
stay_data = cleaned_hotels[
    [
        "property_id",
        "city_id",
        "property_name",
        "property_type",
        "hotel_star_rating",
        "site_review_rating",
        "site_review_count",
        "hotel_facilities",
        "latitude",
        "longitude"
    ]
].copy()

In [113]:
stay_data["stay_id"] = stay_data["property_id"].astype(int).astype(str)

In [114]:
stay_data = stay_data[
    [
        "stay_id",
        "city_id",
        "property_name",
        "property_type",
        "hotel_star_rating",
        "site_review_rating",
        "site_review_count",
        "hotel_facilities",
        "latitude",
        "longitude"
    ]
]

In [115]:
print("STAY rows:", len(stay_data))
print("STAY columns:", len(stay_data.columns))
print(stay_data.head())

STAY rows: 3394
STAY columns: 10
    stay_id city_id                 property_name property_type  \
0   1742658    1035                Khirsu By GMVN           204
1   1755986     371           Global Village Ooty           212
5   1756349     371                 The Hill Side           201
6   1737428    1218           Hotel Mountain Face           204
10  1735523     696  The Gaff in Kalimpong-Deluxe           201

    hotel_star_rating  site_review_rating  site_review_count  \
0                 NaN                 NaN                NaN
1                 3.0                 7.6                5.0
5                 NaN                 8.4               81.0
6                 2.0                 6.9               16.0
10                NaN                 9.0               51.0

                                     hotel_facilities   latitude  longitude
0   Bathroom:Toilet paper|Linen|Towels|Bathroom|To...  30.123749  78.793774
1   Bathroom:Toilet paper|Linen|Towels|Bidet|Towel...  11.329595  76.686732
5   Miscellaneous:Non-smoking rooms•Bathroom:Toile...  11.413460  76.718599
6   Bathroom:Toilet paper|Linen|Towels|Towels/Shee...  32.221456  77.195834
10  Parking:Free!\nFree private parking is possibl...  27.059790  88.458610

In [116]:
city_data = cities_df[
    ["id", "name", "state"]
].copy()
city_data.columns = ["city_id", "city_name", "state"]

In [117]:
print("CITY rows:", len(city_data))
print("CITY columns:", len(city_data.columns))
print(city_data.head())

CITY rows: 1221
CITY columns: 3
  city_id  city_name        state
0       1     Mumbai  Maharashtra
1       2      Delhi        Delhi
2       3  Bengaluru    Karnataka
3       4  Ahmedabad      Gujarat
4       5  Hyderabad    Telangana

In [118]:
city_data.to_csv("city_data.csv", index=False)
print("city_data.csv created")

city_data.csv created

In [119]:
print("HOTEL DATASET")
print("Rows:", len(hotels))
print("Columns:", len(hotels.columns))

print("\nMissing property name:", hotels["property_name"].isna().sum())
print("Missing property ID:", hotels["property_id"].isna().sum())
print("Missing city:", hotels["city"].isna().sum())
print("\nCITY MAPPING")
print("Exact + alias mapped:", hotels["city_id"].notna().sum())
print("Unmapped:", hotels["city_id"].isna().sum())

HOTEL DATASET
Rows: 6000
Columns: 32

Missing property name: 590
Missing property ID: 590
Missing city: 18

CITY MAPPING
Exact + alias mapped: 3764
Unmapped: 2236

In [120]:
print("Total:", len(hotels))

print("\nBoth property name and ID present:",
      hotels["property_name"].notna().sum())

print("City mapped:",
      hotels["city_id"].notna().sum())

print("Property + city mapped:",
      (hotels["property_name"].notna() &
       hotels["property_id"].notna() &
       hotels["city_id"].notna()).sum())

Total: 6000

Both property name and ID present: 5410
City mapped: 3764
Property + city mapped: 3394

In [121]:
print("\nUnmapped hotels with property information:")

unmapped = hotels[
    hotels["city_id"].isna() &
    hotels["property_name"].notna() &
    hotels["property_id"].notna()
]

print("Count:", len(unmapped))
print(
    unmapped[
        ["property_name", "city", "state", "latitude", "longitude"]
    ].head(20).to_string(index=False)
)

Unmapped hotels with property information:
Count: 2016
            property_name         city       state  latitude  longitude
            TRH Pipalkoti    pīpalkoti Uttarakhand 30.429540  79.428116
      Swasti house boat 2    kumarakom      Kerala  9.616057  76.428269
     Amrutham Houseboat 2    kumarakom      Kerala  9.632854  76.423570
      Rahi Motel Haridwar     haridwār Uttarakhand 29.946959  78.156489
      Swasti house boat 4    kumarakom      Kerala  9.617157  76.427840
          Oceana Homestay   tiruvallam      Kerala  8.427137  76.961082
              Grand Hotel     haridwār Uttarakhand 29.937243  78.139983
   Center Point Residency  ganpatipule Maharashtra 17.149583  73.273301
Mistletoe Homestay & Cafe       munnar      Kerala 10.018091  77.010495
  Harithavanam Farm House vandiperiyār      Kerala  9.612581  77.069525
           Hotel Premdeep     mātherān Maharashtra 18.985336  73.269796
     The Clive and Curzon        ketti  Tamil Nadu 11.362699  76.728996
            Grand Parkway     tambaram  Tamil Nadu 12.929669  80.119826
          Oceana Homestay   tiruvallam      Kerala  8.427137  76.961082
          Hotel Jaisalkot        dedha   Rajasthan 26.907474  70.790603
       Lotus Tourist Home chottanikara      Kerala  9.932861  76.388951
              Hotel Vegas      shirwal Maharashtra 18.172516  73.953716
             Singla Hotel  hanumāngarh   Rajasthan 29.581925  74.323017
             F. D. Dezire        varca         Goa 15.236210  73.943114
          Oceana Homestay   tiruvallam      Kerala  8.427137  76.961082

In [122]:
stay_data.to_csv("stay_data.csv", index=False)
print("stay_data.csv created")

stay_data.csv created